from django.db import models


class User(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    status = models.CharField(max_length=50)
    age = models.IntegerField()
    email = models.EmailField()
    password = models.CharField(max_length=30)
    class_id = models.IntegerField()
    about = models.CharField(max_length=300)
    birth_date = models.DateField()
    course_cnt = models.IntegerField()
    hours = models.IntegerField()
    progress = models.IntegerField()
    activity = models.IntegerField()


# страница OGE/EGE_...(tst_page.html)
class Task_list_math(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_russian(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_informatics(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_physics(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_biology(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_chemistry(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_history(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_social_studies(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_literature(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_english(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")

class Task_list_geography(models.Model):
    # тема задания(Действия с десятичными дробями)
    topic = models.CharField(max_length=300, default="")
    # задача(В этом задании проверяются умения выполнять арифметические действия с обыкновенными дробями: сложение, вычитание, умножение и деление. Необходимо знать правила приведения дробей к общему знаменателю, сокращения дробей и выполнения основных операций.)
    task_topic = models.CharField(max_length=300, default="")
    # что нужно сделать(вычеслите, рушите уравнение...)
    task = models.CharField(max_length=300, default="")
    # пример(Вычислите значение выражения: 2/3 + 1/4)
    example = models.CharField(max_length=300, default="")
    # вид ответа(Краткий ответ (число или дробь))
    task_type = models.CharField(max_length=300, default="")
    # вид трудности (базовый)
    difficulty = models.CharField(max_length=300, default="")
    # максимальный балл(1 балл)
    mark = models.IntegerField()
    # предмет(Алгебра)
    subject = models.CharField(max_length=300, default="")








